cd eenji.github.io // replace brianmwevi with your username
git add . // alerts git of the updates we need to add to our repo
git commit -m “Initial Commit” // saves the updates added above
git pushlios && cd portfolios
